apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vprofile-mysql-pvc
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 3Gi